module.exports ={
  sample_TextBox: "Sample Textbox",
  sample_gridHeading: "Sample Grid Heading",
  sample_PageHeading: "Sample Page",

  sample_Heading : "API Documentation List Screen",

  app1_docList_useCase: "Use Case",
  app1_docList_route: "Route",
  app1_docList_documentPath: "DocumentPath",
  app1_docList_createdAt: "CreatedAt",
  app1_docList_createdBy: "CreatedBy",
  app1_docList_isActive: "Is Active",
  app1_docList_isSimulated: "Is Simulated",
  app1_docList_actions: "actions",



  
  sample_viewPageHeading: "Sample View Page",
  APIDefinitionScreen_Heading: "API definition page",
  APIDefScreen_route: "Route",
  APIDefScreen_isActive:"isActive",
  APIDefScreen_Authorization: "Authorization",
  APIDefScreen_Label1:"Dynamic Route Calling",
  APIDefScreen_RouteOveride:"RouteOverride",
  APIDefScreen_fieldName:"FieldName",
  APIDefScreen_Label2:"Custom Function File",
  APIDefScreen_CustomMapping:"Custom Mapping",
  APIDefScreen_MFunctionName:"Mapping Function Name",
  APIDefScreen_CFileName:"Custom File Name",
  APIDefScreen_Label3:"Message Type",
  APIDefScreen_async:"Asynchronous",

  APIDefScreen_Dropdown2:"dropDown2",
  APIDefScreen_RSQueue:"Request Service Queue",
  APIDefScreen_ServiceIP:"ServiceIP",
  APIDefScreen_ResponseQueue:"Response Queue",
  APIDefScreen_isSimulated:"isSimulated",
  APIDefScreen_ServicePort:"Service Port",
  APIDefScreen_Label4:"API Description",
  APIDefScreen_Label5:"Simulator Response",
  APIDefScreen_RequestMapping:"Request Mapping",
  APIDefScreen_ResponseMapping:"Response Mapping",
  SampleCrudPage_Date: "Date",
  SampleCrud_Popup: "Popup Section",
  SampleCrud_InputGrid: "Input Grid Section",
  SampleCrud_Grid_Code: "Code",
  SampleCrud_Grid_Description: "Description",
  SampleCrud_Grid_Quantity: "Quantity",
  SampleCrud_Grid_Value: "Value",
  SampleCrud_Grid_Action: "Action",
  SampleCrud_Grid_Container: "Container",
  SampleCrud_AttachementSection: "Attachment Section",
  SampleDashboard_Heading: "Sample Dashboard",
  SampleDashboardType2_Heading: "Sample Dashboard Type 2",
  sampleGraphFirstLegend: "First",
  sampleGraphSecondLegend: "Second",
  sampleGraphThirdLegend: "Third",
  sampleGraphxaxis: "sample x-axis",
  sampleGraphyaxis: "sample x-axis",
  sampleGrid_column1: "Column 1 - Image",
  sampleGrid_column2: "Column 2",
  sampleGrid_column3: "Column 3",
  sampleGrid_column4: "Column 4",
  sampleGrid_column5: "Column 5",
  sampleGrid_column6: "Column 6",
  sampleGrid_action: "Action",
  sampleGrid_status: "Status",
  sampleDropDownWatermark: "Sample Dropdown",
  sampleInputHeading: "Sample Input Section",
  sample_Dropdown: "Sample Dropdown",
  sample_Label1: "Label 1",
  sample_Label2: "Label 2",
  sample_Label3: "Label 3",
  sample_Label4: "Label 4",
  SampleBlockchain_AccountInfoInsert: "Insert Account Information",
  SampleBlockchain_AccountList: "Account List",
  SampleBlockchain_AccountName: "Name",
  SampleBlockchain_AccountBalance: "Balance"
};