import ARResourcesIndex from '../../applications/constants/ARResourcesIndex';

module.exports = {
  ...ARResourcesIndex,
  breadcrumbHome: "الصفحة الرئيسية ",
  batchView_Heading: "عرض المجموعة ",
  EntityWorkboard_Heading: "لوحة عمل المؤسسة المالية ",
  header_pending: "معلق ",
  header_view_all: "عرض الكل ",
  tile_RECON: "المطابقة ",
  tile_progress: "التقدم ",
  header_logout: "خروج ",
  Notifications_Heading: "إشعارات ",
  wgt_system: "نظام ",
  takeAction: "اتخاذ إجراء ",
  Footer: "2016-2017 افانزا سولوشنز برايفت ليمتد ",
  EWB_name: "اسم المؤسسة المالية ",
  EWB_lastSettlementDate: "تاريخ آخر تسوية ",
  EWB_overDue: "مستحق ",
  EWB_settlementPeriod: "فترة التسوية ",
  EWB_totalTransaction: "إجمالي المعاملة ",
  EWB_pendingExceptions: "الاستثناءات المعلقة ",
  EWB_refundFiled: "الإرجاعات المقدمة ",
  EWB_lastDateRecon: "تاريخ آخر مطابقة ",
  EWB_disputesFiled: "الاعتراضات المقدمة ",
  EWB_actions: "الإجراء ",
  AWB_name: "اسم مزود الخدمات ",
  AWB_lastSettlementDate: "تاريخ آخر تسوية ",
  AWB_overDue: "مستحق ",
  AWB_settlementPeriod: "فترة التسوية ",
  AWB_totalTransaction: "إجمالي المعاملة ",
  AWB_pendingExceptions: "الاستثناءات المعلقة ",
  AWB_refundFiled: "الإرجاعات المقدمة ",
  AWB_lastDateRecon: "تاريخ آخر مطابقة ",
  AWB_disputesFiled: "الاعتراضات المقدمة ",
  AWB_actions: "الإجراء ",
  LastSettlementDate: "تاريخ آخر تسوية ",
  PreviousResolvedExceptions: "الاستثناءات السابقة المقررة ",
  CurrentPeriodTrans: "معاملة الفترة الحالية ",
  ProcessedPastRefund: "الإرجاعات السابقة المنفذة ",
  TotalPayable: "الإجمالي المستحق الدفع ",
  ToDate: "حتى تاريخ ",
  NetTotalAmount: "صافي المبلغ الإجمالي ",
  TotalCommissionAmount: "مبلغ العمولة الإجمالي ",
  TotalAmount: "المبلغ الإجمالي ",
  Commission: "العمولة ",
  AppliedCommission: "العمولة المطبقة ",
  RefundCommission: "عمولة الإرجاعات ",
  TotalCommission: "إجمالي العمولة ",
  ShowBreackupCommission: "عرض تفاصيل العمولة ",
  Download: "تنزيل ",
  BlockChainAddress: "عنوان بلوك تشين ",
  DownloadFileMessage: "يرجى تنزيل الملف ",
  SettlementBatchExecutedMessage: "مجموعة التسوية المنفذة عرض كـ",
  ViewCommissionBreakup: "عرض تفاصيل العمولة ",
  CommissionBreakup: "تفاصيل العمولة ",
  Process: "معالجة ",
  Reconcile: "مطابقة ",
  AquirerWorkboard_Heading: "لوحة عمل مزود الخدمات ",
  AWB_acquirer: "مزود الخدمات ",
  AWB_position: "الوضع ",
  AWB_lastReconDate: "تاريخ آخر مطابقة ",
  AWB_lastCommissionDisbusal: "آخر صرف ",
  AWB_commissions: "العمولات ",
  AWB_refunded: "المرتجع ",
  SL_entityName: "اسم المؤسسة المالية ",
  SL_batchNo: "رقم المجموعة ",
  SL_dateInitiated: "تاريخ البداية ",
  SL_amount: "المبلغ ",
  SL_commission: "العمولة ",
  SL_status: "الحالة ",
  SL_action: "الإجراء ",
  SettlementList_Heading: "قائمة التسوية ",
  SB_PaymentMode: "طريقة الدفع ",
  SB_CardType: "نوع البطاقة ",
  SB_SettledAmount: "المبلغ الذي تم تسويته ",
  SB_TotalNoTrans: "إجمالي عدد المعاملات ",
  SB_InvoiceAmount: "مبلغ الفاتورة ",
  SB_RefundedAmount: "المبلغ المرتجع ",
  SB_RefundedTran: "المعاملة المرتجعة ",
  SB_RefundedCharges: "الرسوم المرتجعة ",
  SB_FinalInvoiceAmount: "مبلغ الفاتورة النهائية ",
  COM_AB_Process: "المعالجة ",
  SB_Heading: "التسويات المعلقة ",
  PS_Heading: "التسويات المنفذة ",
  EL_entity: "اسم المؤسسة المالية ",
  EL_processor: "المعالج ",
  EL_date: "التاريخ ",
  EL_exceptionType: "نوع الاستثناء ",
  EL_userID: "هوية المستخدم ",
  grd_exceptionList: "قائمة الاستثناء ",
  EL_Header: "الاستثناءات ",
  EL_actions: "الإجراءات ",
  EL_ePayRef: "مرجع الدفع الالكتروني ",
  TL_entity: "مزود الخدمة ",
  TL_SPTransNo: "رقم معاملة مزود الخدمة ",
  TL_DEGTransNo: "رقم معاملة دي اي جي ",
  TL_PGTransNo: "رقم معاملة بيه جي ",
  TL_ServiceProvider: "مزود الخدمة ",
  TL_Service: "الخدمة ",
  TL_TransactionDate: "تاريخ المعاملة ",
  TL_Status: "الحالة ",
  TL_Amount: "المبلغ ",
  TL_actions: "الإجراءات ",
  TL_Heading: "قائمة المعاملة ",

  entityName: "الاسم ",
  arabicName: "الاسم باللغة العربية ",
  isActive: "فعال ",
  parentEntity: "المؤسسة المالية الأم ",
  shortCode: "رمز مختصر ",
  legacyCode: "رمز ............",
  GISAccountNo: "حساب جي آى اس ",
  commissionTemplate: "نماذج العمولة ",
  exemptedTillDate: "معفي حتى تاريخ ",
  notifyBeforeMonth: "إخطار قبل (شهر) ",
  settlementType: "التسوية ",
  SettlementCriteria: "معايير التسوية ",
  autoPeriod: "أيام الفترة الآلية ",
  escalationAfter: "تصعيد/ زيادة بعد أيام ",
  integrationType: "نوع المطابقة ",
  fileFormatTemplate: "نموذج تنسيق الملف ",
  noOfDays: "أيام فترة المطابقة ",
  username: "اسم المستخدم ",
  password: "كلمة المرور ",
  EntitySetup_Heading: "إنشاء مؤسسة مالية ",
  EntitySearchContainer_Heading: "بحث مؤسسة مالية ",
  ES_serviceName: "اسم الخدمة ",
  ES_serviceCode: "رمز الخدمة ",
  ES_contactName: "اسم مسؤول الاتصال ",
  ES_email: "البريد الالكتروني ",
  ES_mobile: "متحرك ",
  ES_sFTPServer: "sFTP Server",
  ES_port: "منفذ/ مخرج ",
  ES_services_action: "الإجراء ",
  ES_contacts_action: "الإجراء ",
  ESEARCH_entityName: "اسم المؤسسة المالية ",
  ESEARCH_arabicName: "الاسم باللغة العربية ",
  ESEARCH_status: "الحالة ",
  ESEARCH_shortCode: "رمز مختصر ",
  ESEARCH_orgType: "Org Type",
  ESEARCH_isActive: "فعال ",
  ESEARCH_action: "الإجراء ",

  /** 26-09-2017 */
  Refund_Heading: "Initiate Refund",
  IR_searchHeading: "Refund Information",
  IR_uploadHeading: "Upload / Comment",
  viewRefund_Heading: "View Refund",
  GEN_File: "اسم الملف ",
  GEN_Action: "الإجراء ",
  GEN_date: "التاريخ ",
  GEN_userID: "هوية المستخدم ",
  GEN_org: "المؤسسة ",
  GEN_comments: "التعليقات ",
  VR_searchHeading: "تفاصيل الإرجاع ",
  RL_searchHeading: "بحث المعاملة ",
  RL_refundList: "المعاملات المرتجعة ",
  RefundList_Heading: "قائمة الإرجاع ",
  ID_searchHeading: "Dispute Information",
  ID_uploadHeading: "Upload / Comment",
  Dispute_Heading: "Initiate Dispute",
  viewDispute_Heading: "View Dispute",
  DL_searchHeading: "Transaction Search",
  DL_disputeList: "Disputed Transactions",
  RefundList_Heading: "Refund List",

  DisputeList_Heading: "Dispute List",

  btn_cancel: {
    "displayText": "Cancel",
    "displayClass": "btn primary"
  },
  btn_save: {
    "displayText": "Cancel",
    "displayClass": "btn primary"
  },


  /* new Test */

  MRS_type: "النوع ",
  MRS_count: "المحاسبة ",
  MR_Process: "المعالجة ",
  MR_Reconile: "المطابقة ",
  MRS_action: "الإجراء ",
  ManualRecon_Heading: "مطابقة يدوية ",

  MRA_date: "Date",
  MRA_reconAction: "Action",
  MRA_entityType: "Entity Type",
  MRA_fileName: "File Name",
  MRA_userID: "User ID",
  MRA_action: "Record Details",

  CB_Heading: "صرف العمولة ",
  CB_summary: "ملخص ",
  CB_amount: "المبلغ ",
  CB_count: "المحاسبة ",
  CB_LastCommissionDate: "تاريخ آخر عمولة ",
  CB_ToDate: "حتى تاريخ ",
  CB_CommissionSummary: "ملخص العمولة ",
  CB_UploadFile: "حمل الملفات ",
  CB_BAT_Process: "المعالجة ",

  CBP_Heading: "Commission Disbursal",
  CBP_Download: "Download",
  CBP_DownloadMessage: "Please download the file",
  CBP_BlockChainAddress: "Blockchain Address",
  CBP_CommissionBatchMessage: "Commission batch is executed view as",

  CL_Heading: "عرض العمولات المصروفة السابقة ",
  CL_SearchHeading: "مرشحات العمولة المصروفة السابقة ",
  CL_GridHeading: "عرض العمولات المصروفة السابقة ",
  CL_Processor: "المعالج ",
  CL_RefNo: "رقم المرجع ",
  CL_StartDate: "من تاريخ ",
  CL_EndDate: "حتى تاريخ ",
  CL_Date: "التاريخ ",
  CL_AmountAED: "المبلغ (بالدرهم الإماراتي) ",
  CL_UserID: "هوية المستخدم ",
  CL_Commission: "العمولات ",
  CL_actions: "الإجراء ",
  RL_refNo: "رقم المرجع ",
  RL_date: "التاريخ ",
  RL_entity: "المؤسسة المالية ",
  RL_status: "الحالة ",
  RL_action: "الإجراء ",
  CD_Summary: "Summary",
  CD_Amount: "Amount",
  CD_Count: "Count",


  CBV_SPRefNo: "SP Ref. No.",
  CBV_DGRefNo: "DG Ref. No.",
  CBV_PFRefNo: "PG Ref. No.",
  CBV_TranData: "Data of Tran",
  CBV_Amount: "Amount",
  CBV_Status: "Status",
  CBV_BlocchainID: "Blockchain No.",
  CBV_action: "Additional Detail",

  // 10/10/17
  ASEARCH_acquirerName: "Acquirer Name",
  ASEARCH_arabicName: "Arabic Name",
  ASEARCH_status: "Status",
  ASEARCH_shortCode: "Short Code",
  ASEARCH_isActive: "Active",
  ASEARCH_action: "Actions",
  AS_acquirerName: "Acquirer Name",
  AS_contactName: "Contact Name",
  AS_email: "Email",
  AS_mobile: "Mobile",
  AS_contacts_action: "Actions",
  AS_fundsTransferSLAPeriod: "Funds Transfer SLA Period(Days)",
  AS_shadowAccount: "Shadow Account",

  FTEMP_fileType: "نوع الملف ",
  FTEMP_template_action: "الإجراءات ",
  FTEMP_templateName: "اسم النموذج ",
  FTEMP_separator: "الفاصل ",
  FTEMP_columnNo: "رقم العمود ",
  FTEMP_fieldNameTag: "إشارة اسم الحقل ",
  FTEMP_fieldName: "اسم الحقل ",
  FTEMP_internalField: "الحقل الداخلي ",
  FTEMP_specialFunction: "وظيفة خاصة ",
  FTEMP_param1: "مؤشر 1 ",
  FTEMP_param2: "مؤشر 2 ",
  FTEMP_fields_action: "الإجراءات ",
  FTEMP_required: "مطلوب ",
  FTEMP_fieldFormat: "تنسيق الحقل (ريجيكس) ",
  FTEMP_maxLength: "الحد الأقصى للطول ",
  FTEMP_dataType: "نوع البيانات ",
  FTEMP_XMLMainTag: "الإشارة الرئيسية لـ اكس ام ال ",
  CTEMP_templateName: "اسم النموذج ",
  CTEMP_cardType: "نوع البطاقة ",
  CTEMP_feeType: "نوع الرسم ",
  CTEMP_startDate: "تاريخ البدء ",
  CTEMP_endDate: "تاريخ الانتهاء ",
  CTEMP_minVal: "الحد الأدنى للمعاملة (بالدرهم الإماراتي) ",
  CTEMP_maxVal: "الحد الأقصى للمعاملة (بالدرهم الإماراتي) ",
  CTEMP_flatRate: "ثابت ",
  CTEMP_percentageRate: "النسبة المئوية ",
  CTEMP_template_action: "الإجراءات ",

  ETEMP_templateName: "Template Name",
  ETEMP_subjectEng: "English Subject",
  ETEMP_subjectArabic: "Arabic Subject",
  ETEMP_templateType: "Type",
  ETEMP_templateTextEng: "Text Eng",
  ETEMP_templateTextArabic: "Text Arabic",
  ETEMP_placeHolder: "Place Holder",
  ETEMP_template_action: "Actions",


  RSEARCH_roleName: "Name",
  RSEARCH_roleDescription: "Description",
  RSEARCH_roleAction: "Action",
  USEARCH_userID: "User ID",
  USEARCH_firstName: "First Name",
  USEARCH_lastName: "Last Name",
  USEARCH_isActive: "Status",
  USEARCH_userAction: "Action",
  RList_roleName: "Name",
  RList_description: "Description",
  RList_roleID: "Role ID",
  WCD_exception: "Exception",
  WCD_start: "Start",
  WCD_end: "End",

  FU_fileName: "File Name",
  FU_dropMessage: "Drop files here or click to upload",
  FU_removeFileMessage: "Remove File",

  Tabel_noRecordFoundMessage: "No record found",

  TL_tranDetailHeading: "Transaction Detail",
  TL_tranPageHeading: "Transaction",

  EL_Heading: "Exception List",
  RA_Heading: "Recon Audit Trail",
  ES_Heading: "Entity Setup",
  ESearch_Heading: "Entity Search",
  AQSearch_Heading: "Acquirer Search",
  AQSetup_Heading: "Acquirer Setup",
  ETSetup_Heading: "Email Template Setup",
  CSearch_Heading: "Commission Search",
  CSetup_Heading: "Commission Setup",
  FTSearch_Heading: "File Template Search",
  FTSetup_Heading: "File Template Setup",
  GSearch_Heading: "Group Search",
  GSetup_Heading: "Group Setup",
  USearch_Heading: "User Search",
  USetup_Heading: "User Setup",

  TLP_SearchFilter: "Transaction Search Filter",
  TLP_DetailHeading: "Transaction Detail",
  TLP_GridTitle: "Transactions",
  TLP_Close: "Close",
  TLPF_Entity: "Entity",
  TLPF_Processor: "Processor",
  TLPF_TranStatus: "Tran Status",
  TLPF_DEGRefNo: "DEG Ref No",
  TLPF_SPRefNo: "SP Ref No",
  TLPF_PGRefNo: "PG Ref No",
  TLPF_FromDate: "From Date",
  TLPF_ToDate: "To Date",
  TLPF_ExceptionType: "Exception Type",


  Loading: "Loading..",
  Search: "Search",
  Clear: "Clear",
  Close: "Close",

  TD_ReferenceNo: "Reference No",
  TD_DEGRefNo: "DEG Ref No",
  TD_SPRefNo: "SP Ref No",
  TD_PGRefNo: "PG Ref No",
  TD_RefundRefNo: "Refund Reference No",
  TD_SettlementRefNo: "Settlement Ref No",
  TD_InvoiceRefNo: "Invoice Reference No",
  TD_StatusIndicator: "Status Indicator",
  TD_DEGCapNo: "DEG Cap No",
  TD_PGStatus: "PG Status",
  TD_SPReconStatus: "SP Recon Status",
  TD_DEGStatus: "DEG Status",
  TD_PGReconStatus: "PG Recon Status",
  TD_AcqReconStatus: "Acquirer Recon Status",
  TD_ManuallyRecon: "Manually Reconciled",
  TD_ConfirmSerDel: "Confirm Service Delivery",
  TD_OtherDetail: "Other Detail",
  TD_Entity: "Entity",
  TD_PaymentGateway: "Payment Gateway",
  TD_Service: "Service",
  TD_PaymentChannel: "Payment Channel",
  TD_TransactionReqDate: "Transaction Requested Date",
  TD_PaymentMethod: "Payment Method",
  TD_TranCapDate: "Transaction Capture Date",
  TD_CardType: "Card Type",
  TD_RefColl: "Refund Cancellation Remarks",
  TD_Amount: "Amount",
  TD_ePay: "ePay",
  TD_CustomerEmail: "Customer Email",
  TD_CustomerMobile: "Customer Mobile",
  TD_IPAddress: "IP Address",
  TD_RefundStatus: "Refund Status",
  TD_DisputeStatus: "Dispute Status",

  EL_TransactionDetail: "Transaction Detail",
  ES_ExceptionsSearchFilter: "Exceptions Search Filter",

  MR_LastReconDate: "Last Recon Date",

  AcquirerDetailReport_Heading: "Acquirer Detail Report",

  RPT_Entity: "اسم المؤسسة المالية",
  RPT_FromDate: "From Date",
  RPT_ToDate: "To Date",
  RPT_CardType: "Card Type",
  RPT_PaymentMethod: "Payment Method",
  RPT_TransactionStatus: "Transaction Status",
  RPT_ReportFormat: "Report Format",
  RPT_PaymentGateway: "Payment Gateway",
  RPT_Acquirer: "مزود الخدمات",
  ChangePassword_ChangePassword: "Change Password",

  RV_fileName: "File Name",
  RV_status: "Status",
  RV_uploadedOn: "Uploaded on",
  RV_uploadedBy: "Uploaded By",

  SLA_img: "User Name",
  SLA_belowSLA: "Below SLA",
  SLA_MeetSLA: "Meet SLA",
  SLA_userId: "User ID",
  SLA_Cnt: "Total Count",
  SLA_Actions: "Actions",
  SLAWorkboard_Heading: "SLA",

  ChangeTrackingFilters:"Change Tracking Filters",
  PrivateCollection:"Private Collection",
  KEY:"KEY",
  ChangeTrackingListData:"Change Tracking List Data"

};
