module.exports ={
  sample_TextBox: "Sample Textbox",
  sample_gridHeading: "Sample Grid Heading",
  sample_PageHeading: "Sample Page",
  sample_viewPageHeading: "Sample View Page",
  SampleCrudPage_Heading: "Sample Crud Page",
  SampleCrudPage_Textbox: "Textbox",
  SampleCrudPage_Dropdown: "Dropdown",
  SampleCrudPage_Date: "Date",
  SampleCrud_Popup: "Popup Section",
  SampleCrud_InputGrid: "Input Grid Section",
  SampleCrud_Grid_Code: "Code",
  SampleCrud_Grid_Description: "Description",
  SampleCrud_Grid_Quantity: "Quantity",
  SampleCrud_Grid_Value: "Value",
  SampleCrud_Grid_Action: "Action",
  SampleCrud_Grid_Container: "Container",
  SampleCrud_AttachementSection: "Attachment Section",
  SampleDashboard_Heading: "Sample Dashboard",
  SampleDashboardType2_Heading: "Sample Dashboard Type 2",
  sampleGraphFirstLegend: "First",
  sampleGraphSecondLegend: "Second",
  sampleGraphThirdLegend: "Third",
  sampleGraphxaxis: "sample x-axis",
  sampleGraphyaxis: "sample x-axis",
  sampleGrid_column1: "Column 1 - Image",
  sampleGrid_column2: "Column 2",
  sampleGrid_column3: "Column 3",
  sampleGrid_column4: "Column 4",
  sampleGrid_column5: "Column 5",
  sampleGrid_column6: "Column 6",
  sampleGrid_action: "Action",
  sampleGrid_status: "Status",
  sampleDropDownWatermark: "Sample Dropdown",
  sampleInputHeading: "Sample Input Section",
  sample_Dropdown: "Sample Dropdown",
  sample_Label1: "Label 1",
  sample_Label2: "Label 2",
  sample_Label3: "Label 3",
  sample_Label4: "Label 4",
  SampleBlockchain_AccountInfoInsert: "Insert Account Information",
  SampleBlockchain_AccountList: "Account List",
  SampleBlockchain_AccountName: "Name",
  SampleBlockchain_AccountBalance: "Balance"
};