export const GENRAL_LOAD_SUCCESS = 'GENRAL_LOAD_SUCCESS';
export const GENRAL_LOAD_FAILURE = 'GENRAL_LOAD_FAILURE';

export const GENRAL_INSERT_SUCCESS = 'GENRAL_INSERT_SUCCESS';
export const GENRAL_INSERT_FAILURE = 'GENRAL_INSERT_FAILURE';

export const GENRAL_UPDATE_SUCCESS = 'GENRAL_UPDATE_SUCCESS';
export const GENRAL_UPDATE_FAILURE = 'GENRAL_UPDATE_FAILURE';


export const GENRAL_DELETE_SUCCESS = 'GENRAL_DELETE_SUCCESS';
export const GENRAL_DELETE_FAILURE = 'GENRAL_DELETE_FAILURE';


export const GENRAL_LOGIN_SUCCESS = 'GENRAL_LOGIN_SUCCESS';
export const GENRAL_LOGIN_FAILURE = 'GENRAL_LOGIN_SUCCESS';


export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILURE = 'FORGET_PASSWORD_FAILURE';

export const GENRAL_LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const GENRAL_LOG_OUT_FAILURE = 'GENRAL_LOG_OUT_FAILURE';